### ISSUE TITLE
Page movie

### ISSUE THREAD

**Issue by bpaquier** [bpaquier/tp-react-cine#35]
- [ ] Ajouter un bouton qui mène sur le lien officiel du film et cela sur safari, attention le bouton doit être toujours visible 
- [x] Changer le nom de la page en details/id
- [ ] ajouter un param qui permet de set le end point de la page (movie OR tvshow)
- [x] alignement layout en mobile
- [x] Sur la page ou un seul movie s'affiche, afficher tous les champs conditionnellement
- [x] Ajouter le nombre de personnes qui a voté à côté des étoiles

**Comment by nb-plk** [comment]
bande de bg
